### ISSUE TITLE
Overcounting sample counts in ogg opus

### ISSUE THREAD

**Issue by skijit** [eshaz/codec-parser#31]
Hi, 

Thanks for sharing this code. 

I noticed that the opus parser produces a total sample count that is somewhat higher than what I get from decoding (using your decoding libraries or opusdec directly).

For a simple repro, see this [repo](https://github.com/skijit/ogg-opus-decode-vs-parse-test).

It looks like most of the frames from the parser have 960 samples, including, conspicuously the last frame.  Also, all the opus files I've tested with the parser have total sample counts divisible by 960.  Perhaps the last frame is being padded?

Or maybe I'm using it wrong!

Thanks again!

**Comment by eshaz** [comment]
Thanks for submitting this issue. I think you're using the libraries cirrectly

**Comment by eshaz** [comment]
Didn't mean to close the issue, was typing on my phone and miss-clicked.

**Comment by eshaz** [comment]
Thanks for submitting this issue. You're using the libraries correctly.

The Ogg container specifies how many samples are in each page with the absolute granule position property. The decoder libraries are trimming the pages to only return the decoded samples, but it looks like I missed this in codec-parser. Each Opus frame has a known sample length in milliseconds, but the Ogg container is used to trim out any padding at the end. Should be a simple fix. I'll take a look at this later today.

Opus frame length mappings: https://github.com/eshaz/codec-parser/blob/3ad03848bb12c57f297cf40c01fab6d208332f6a/src/codecs/opus/OpusHeader.js#L124-L157

Where the frame length gets set: https://github.com/eshaz/codec-parser/blob/3ad03848bb12c57f297cf40c01fab6d208332f6a/src/codecs/opus/OpusHeader.js#L252

Where the frame samples get calculated, and currently not considering the actual Ogg decoded samples: https://github.com/eshaz/codec-parser/blob/3ad03848bb12c57f297cf40c01fab6d208332f6a/src/codecs/opus/OpusFrame.js#L27

**Comment by skijit** [comment]
Super- thanks!

**Comment by eshaz** [comment]
I've released a new version that should fix this. Let me know if you still see this issue.

**Comment by skijit** [comment]
Great- thank you!
